### PR TITLE
Mocks added for statutils

### LINKED ISSUE #118: Need to add mock stats in sanity test
/kind bug

**What happened?**
Currently sanity tests don't have mock for stats object in node service. 
stats object was recently added in the node service when getVolumeStats was implemented.
 **Commit**  : https://github.com/kubernetes-sigs/ibm-powervs-block-csi-driver/commit/4ba7312e956dcedfa7b0d8ea45ac49ff305083d3
But, necessary changes were not made in sanity tests. 
This causes failures in sanity tests. Need to add mock methods to avoid sanity test failures.

**Reference:** https://github.com/kubernetes-sigs/ibm-vpc-block-csi-driver/blob/9c4865260a0d3b816fa2c3cb63f250a5870c4adc/tests/sanity/sanity_test.go#L170

**What you expected to happen?**
Adding can make a successful sanity run.

**How to reproduce it (as minimally and precisely as possible)?**
`go test -v pkg/driver/sanity_test.go`

### PR DESCRIPTION
**Pull request by Madhan-SWE**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Mocks added for StatUtils in sanity tests.

**Which issue(s) this PR fixes**:
Fixes #118

### CODE REVIEW

File: pkg/driver/sanity_test.go [hunk 1]
```diff
@@ -18,20 +18,25 @@ import (
...
 	}
 	defer os.RemoveAll(dir)
 
-	targetPath := filepath.Join(dir, "mount")
+	TargetPath = filepath.Join(dir, "mount")
 	stagingPath := filepath.Join(dir, "staging")
 	endpoint := "unix://" + filepath.Join(dir, "csi.sock")
 
 	config := &sanity.Config{
-		TargetPath:       targetPath,
```
Comment (mkumatag) [inline pkg/driver/sanity_test.go:34]: I'm wondering whether we can just pass this `targetPath` into the `MockStatSanity` struct and use it instead of making this global?

**Review by mkumatag — CHANGES_REQUESTED** [review]

File: pkg/driver/sanity_test.go (hunk 1 above)
Comment (Madhan-SWE) [reply pkg/driver/sanity_test.go]: Modified as suggested.

**Review by mkumatag — APPROVED** [review]
/lgtm
/approve
