### PR TITLE
reduce multipathd usage as it timeout if large number of disks (OCPBUGS-16878)

### LINKED ISSUE #261: Doesn't use the multipath devices for mounting to the target volume
/kind bug

**What happened?**

While running the tests found that it is not using the multipath device while mounting the target, e.g:

```shell
I1002 16:23:46.166197       1 node.go:98] NodeStageVolume: called with args {VolumeId:dc2550d7-2a61-44dc-a123-442286b10e6a PublishContext:map[wwn:60050768108002c0c000000000022d19] StagingTargetPath:/var/lib/kubelet/plugins/kubernetes.io/csi/powervs.csi.ibm.com/7c95f38c1ecbcd1f4ac780a8d93623a2569590a5a710416a5cfec32bfe74eb85/globalmount VolumeCapability:mount:<fs_type:"xfs" > access_mode:<mode:SINGLE_NODE_WRITER >  Secrets:map[] VolumeContext:map[storage.kubernetes.io/csiProvisionerIdentity:1664711988348-8081-powervs.csi.ibm.com] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
ERROR: logging before flag.Parse: I1002 16:23:46.166345       1 fibrechannel.go:252] Attaching fibre channel volume
I1002 16:23:46.199725       1 node.go:180] NodeStageVolume: find device path for wwn 60050768108002c0c000000000022d19 -> /dev/sdm
I1002 16:23:46.200531       1 node.go:198] NodeStageVolume: formatting /dev/sdm and mounting at /var/lib/kubelet/plugins/kubernetes.io/csi/powervs.csi.ibm.com/7c95f38c1ecbcd1f4ac780a8d93623a2569590a5a710416a5cfec32bfe74eb85/globalmount with fstype xfs
I1002 16:23:46.200550       1 mount_linux.go:405] Attempting to determine if disk "/dev/sdm" is formatted using blkid with args: ([-p -s TYPE -s PTTYPE -o export /dev/sdm])
I1002 16:23:46.207600       1 mount_linux.go:408] Output: "", err: exit status 2
I1002 16:23:46.207621       1 mount_linux.go:366] Disk "/dev/sdm" appears to be unformatted, attempting to format as type: "xfs" with options: [/dev/sdm]
I1002 16:24:07.586122       1 mount_linux.go:376] Disk successfully formatted (mkfs): xfs - /dev/sdm /var/lib/kubelet/plugins/kubernetes.io/csi/powervs.csi.ibm.com/7c95f38c1ecbcd1f4ac780a8d93623a2569590a5a710416a5cfec32bfe74eb85/globalmount
I1002 16:24:07.586161       1 mount_linux.go:394] Attempting to mount disk /dev/sdm in xfs format at /var/lib/kubelet/plugins/kubernetes.io/csi/powervs.csi.ibm.com/7c95f38c1ecbcd1f4ac780a8d93623a2569590a5a710416a5cfec32bfe74eb85/globalmount
I1002 16:24:07.586195       1 mount_linux.go:146] Mounting cmd (mount) with arguments (-t xfs -o defaults /dev/sdm /var/lib/kubelet/plugins/kubernetes.io/csi/powervs.csi.ibm.com/7c95f38c1ecbcd1f4ac780a8d93623a2569590a5a710416a5cfec32bfe74eb85/globalmount)
I1002 16:24:08.349667       1 node.go:457] NodeGetCapabilities: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I1002 16:24:08.374846       1 node.go:457] NodeGetCapabilities: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I1002 16:24:08.375431       1 node.go:457] NodeGetCapabilities: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I1002 16:24:08.376121       1 node.go:308] NodePublishVolume: called with args {VolumeId:dc2550d7-2a61-44dc-a123-442286b10e6a PublishContext:map[wwn:60050768108002c0c000000000022d19] StagingTargetPath:/var/lib/kubelet/plugins/kubernetes.io/csi/powervs.csi.ibm.com/7c95f38c1ecbcd1f4ac780a8d93623a2569590a5a710416a5cfec32bfe74eb85/globalmount TargetPath:/var/lib/kubelet/pods/b50a147a-0d83-4d2d-8cde-deddd2ff8036/volumes/kubernetes.io~csi/pvc-b00fd2ab-fa8c-4098-90d4-c274b8cb0dc7/mount VolumeCapability:mount:<fs_type:"xfs" > access_mode:<mode:SINGLE_NODE_WRITER >  Readonly:false Secrets:map[] VolumeContext:map[storage.kubernetes.io/csiProvisionerIdentity:1664711988348-8081-powervs.csi.ibm.com] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I1002 16:24:08.376230       1 node.go:560] NodePublishVolume: creating dir /var/lib/kubelet/pods/b50a147a-0d83-4d2d-8cde-deddd2ff8036/volumes/kubernetes.io~csi/pvc-b00fd2ab-fa8c-4098-90d4-c274b8cb0dc7/mount
I1002 16:24:08.376403       1 node.go:570] NodePublishVolume: mounting /var/lib/kubelet/plugins/kubernetes.io/csi/powervs.csi.ibm.com/7c95f38c1ecbcd1f4ac780a8d93623a2569590a5a710416a5cfec32bfe74eb85/globalmount at /var/lib/kubelet/pods/b50a147a-0d83-4d2d-8cde-deddd2ff8036/volumes/kubernetes.io~csi/pvc-b00fd2ab-fa8c-4098-90d4-c274b8cb0dc7/mount with option [bind] as fstype xfs
I1002 16:24:08.376433       1 mount_linux.go:146] Mounting cmd (mount) with arguments (-t xfs -o bind /var/lib/kubelet/plugins/kubernetes.io/csi/powervs.csi.ibm.com/7c95f38c1ecbcd1f4ac780a8d93623a2569590a5a710416a5cfec32bfe74eb85/globalmount /var/lib/kubelet/pods/b50a147a-0d83-4d2d-8cde-deddd2ff8036/volumes/kubernetes.io~csi/pvc-b00fd2ab-fa8c-4098-90d4-c274b8cb0dc7/mount)
I1002 16:24:08.378919       1 mount_linux.go:146] Mounting cmd (mount) with arguments (-t xfs -o bind,remount /var/lib/kubelet/plugins/kubernetes.io/csi/powervs.csi.ibm.com/7c95f38c1ecbcd1f4ac780a8d93623a2569590a5a710416a5cfec32bfe74eb85/globalmount /var/lib/kubelet/pods/b50a147a-0d83-4d2d-8cde-deddd2ff8036/volumes/kubernetes.io~csi/pvc-b00fd2ab-fa8c-4098-90d4-c274b8cb0dc7/mount)
I1002 16:25:19.983352       1 node.go:457] NodeGetCapabilities: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I1002 16:25:19.984326       1 node.go:388] NodeGetVolumeStats: called with args {VolumeId:dc2550d7-2a61-44dc-a123-442286b10e6a VolumePath:/var/lib/kubelet/pods/b50a147a-0d83-4d2d-8cde-deddd2ff8036/volumes/kubernetes.io~csi/pvc-b00fd2ab-fa8c-4098-90d4-c274b8cb0dc7/mount StagingTargetPath: XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I1002 16:25:19.984414       1 node.go:452] FS Volume stats collected: usage:<available:4220735488 total:4284481536 used:63746048 unit:BYTES > usage:<available:2097148 total:2097152 used:4 unit:INODES >
I1002 16:26:28.389337       1 node.go:457] NodeGetCapabilities: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I1002 16:26:28.390048       1 node.go:388] NodeGetVolumeStats: called with args {VolumeId:dc2550d7-2a61-44dc-a123-442286b10e6a VolumePath:/var/lib/kubelet/pods/b50a147a-0d83-4d2d-8cde-deddd2ff8036/volumes/kubernetes.io~csi/pvc-b00fd2ab-fa8c-4098-90d4-c274b8cb0dc7/mount StagingTargetPath: XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
```

Even thought there is a multipath configured on the system but it is taking additional time to reflecting in the system and end up having lot of dangling devices(both normal and multipath) post deletion of volumes.

**What you expected to happen?**

Instead it should detect the multipath disks and not the normal disks.

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:

This is tested in the RHEL8.x version, found a useful information from this link about configuring the appropriate configuration for the multipath.d improved the performance:

https://access.redhat.com/solutions/137073

modified to following param for the 

```
[root@rdr-mkumatag-csi-2 by-id]# cat /etc/multipath.conf
defaults {
        user_friendly_names yes
        polling_interval 5
        fast_io_fail_tmo 5
        dev_loss_tmo 10
        checker_timeout 15
}
```

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

### PR DESCRIPTION
**Pull request by yussufsh**
**What type of PR is this?**

/kind flake
/kind regression

**What this PR does / why we need it**:

This PR will not use multipathd commands to list paths or maps for calculating the devices used in the CSI driver. Instead dmsetup command is used which is thread-safe and does not time out in case of a large number of disks.
We can find the number of active disks in a path and use it.
Also, we do not need to handle error or faulty paths. Just removing the mpath for faulty (not active) disks we can handle orphans cleanup which ensures the new disks get detected.

**Which issue(s) this PR fixes**:

Fixes #261 (It is already fixed, this PR will improve on same)

**Special notes for your reviewer**:

Integration tests are run on device pkg. Need to do multiple e2e runs, will confirm once done.

**Release note**:
```
none
```

### CODE REVIEW

File: pkg/device/multipath.go [hunk 1]
```diff
@@ -178,109 +72,58 @@ func retryCleanupDeviceAndSlaves(dev *Device) (err error) {
 	return nil
```
Comment (mkumatag) [inline pkg/device/multipath.go:72]: fix the return value as we are not returning anything other than nil here

File: pkg/device/multipath.go [hunk 2]
```diff
@@ -178,109 +72,58 @@ func retryCleanupDeviceAndSlaves(dev *Device) (err error) {
...
-		deletePath := fmt.Sprintf("/sys/block/%s/device/delete", path.Device)
-		if err := deleteSdDevice(deletePath); err != nil {
-			klog.Warningf("error while deleting device %s: %v", path, err)
-			// try to cleanup rest of the paths
-		}
-	}
-
-	return removeErr
+// cleanupDevice remove the multipath devices
+func cleanupDevice(dev *Device) (err error) {
```
Comment (mkumatag) [inline pkg/device/multipath.go:76]: you can directly call `multipathRemoveDmDevice`

File: pkg/device/multipath.go [hunk 3]
```diff
@@ -178,109 +72,58 @@ func retryCleanupDeviceAndSlaves(dev *Device) (err error) {
...
-	defer multipathMutex.Unlock()
-
-	_ = multipathDisableQueuing(dev)
+// multipathRemoveDmDevice remove multipath device via dmsetup
+func multipathRemoveDmDevice(mapper string) (err error) {
+	if strings.HasSuffix(mapper, "mpatha") {
+		klog.Warning("skipping remove mpatha which is root")
+		return
+	}
+	_ = multipathDisableQueuing(mapper)
```
Comment (mkumatag) [inline pkg/device/multipath.go:100]: log the error or handle it instead of ignoring it

File: pkg/device/multipath.go [hunk 4]
```diff
@@ -178,109 +72,58 @@ func retryCleanupDeviceAndSlaves(dev *Device) (err error) {
...
 
-	args := []string{"remove", "--force", dev.Mapper}
+	args := []string{"remove", "--force", mapper}
 	outBytes, err := exec.Command(dmsetupcommand, args...).CombinedOutput()
 	if err != nil {
-		return fmt.Errorf("failed to remove multipath map for %s with wwn %s. Error: %v", dev.Mapper, dev.WWN, err)
+		return fmt.Errorf("failed to remove multipath map for %s, error: %v", mapper, err)
 	}
 	out := string(outBytes)
 	if out != "" && !strings.Contains(out, "ok") && !strings.Contains(out, deviceDoesNotExist) {
```
Comment (mkumatag) [inline pkg/device/multipath.go:108]: can we have function to check this conditions?

**Review by mkumatag — CHANGES_REQUESTED** [review]

File: pkg/device/device.go [hunk 5]
```diff
@@ -145,11 +145,13 @@ func (d *Device) CreateDevice() (err error) {
...
 
 	for {
 		if scanLock.TryLock() {
+			defer scanLock.Unlock()
 			if scan {
+				// always clean orphan paths before scanning hosts
+				cleanupOrphanPaths()
 				err = scsiHostRescan()
 			}
 			return err
```
Comment (mkumatag) [inline pkg/device/device.go:157]:
```suggestion
			func() {
				defer scanLock.Unlock()
				if scan {
					// always clean orphan paths before scanning hosts
					cleanupOrphanPaths()
					err = scsiHostRescan()
				}
			}()
			return
```

**Review by mkumatag — CHANGES_REQUESTED** [review]
